version: "3.8"

services:
  marioapi:
    build:
      context: ./marioapi/
    image: marioapi
    entrypoint: Rscript -e "options('plumber.port'=8082,plumber.host='0.0.0.0');library(future);plan(multisession);library('marioapi');run_api()"
    restart: always
    ports:
      - 8082:8082
